import json
import numpy as np


class ARXPredictor:
    """
    ARX Q=0.90 inference — one matrix-vector multiply per call.
    Weights loaded from arx_q90_weights.json (generated by export_models.py).
    """

    def __init__(self, weights_path: str) -> None:
        with open(weights_path) as f:
            data = json.load(f)
        self.feature_names: list[str] = data['feature_names']
        self.motors: list[str]        = data['motors']
        self.coef: np.ndarray         = np.array(data['coef'],      dtype=np.float64)  # (4, 31)
        self.intercept: np.ndarray    = np.array(data['intercept'], dtype=np.float64)  # (4,)

    def predict(self, x: np.ndarray) -> np.ndarray:
        """
        x: (31,) feature vector from LagBuffer.get_feature_vector()
        returns: (4,) predicted currents [I_FL, I_FR, I_RL, I_RR] at t+1
        """
        return self.coef @ x + self.intercept
