import json
import numpy as np
import xgboost as xgb
from pathlib import Path


class XGBPredictor:
    """
    XGBoost Q=0.90 inference — 4 independent models (one per motor).
    Weights loaded from xgb_q90_{FL|FR|RL|RR}.ubj (generated by export_models.py).
    """

    MOTOR_NAMES = ('FL', 'FR', 'RL', 'RR')

    def __init__(self, weights_dir: str) -> None:
        weights_dir = Path(weights_dir)
        self.models: dict[str, xgb.XGBRegressor] = {}
        for m in self.MOTOR_NAMES:
            model = xgb.XGBRegressor()
            model.load_model(str(weights_dir / f'xgb_q90_{m}.ubj'))
            self.models[m] = model

        with open(weights_dir / 'xgb_meta.json') as f:
            meta = json.load(f)
        self.feature_names: list[str] = meta['feature_names']

    def predict(self, x: np.ndarray) -> np.ndarray:
        """
        x: (31,) feature vector from LagBuffer.get_feature_vector()
        returns: (4,) predicted currents [I_FL, I_FR, I_RL, I_RR] at t+1
        """
        x2d = x.reshape(1, -1)
        return np.array(
            [self.models[m].predict(x2d)[0] for m in self.MOTOR_NAMES],
            dtype=np.float64,
        )
